-- CreateTable
CREATE TABLE `LOAITAIKHOAN` (
    `idLoaiTK` INTEGER NOT NULL AUTO_INCREMENT,
    `ten` VARCHAR(191) NOT NULL,
    `moTa` VARCHAR(191) NULL,

    PRIMARY KEY (`idLoaiTK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NGUOIDUNG` (
    `idNguoiDung` INTEGER NOT NULL AUTO_INCREMENT,
    `idLoaiTK` INTEGER NOT NULL,
    `idViTri` INTEGER NOT NULL,
    `idTinhThanh` INTEGER NOT NULL,
    `idCapDo` INTEGER NOT NULL,
    `ten` VARCHAR(191) NOT NULL,
    `ngaySinh` DATETIME(3) NOT NULL,
    `sdt` VARCHAR(191) NOT NULL,
    `diaChi` VARCHAR(191) NULL,
    `email` VARCHAR(191) NOT NULL,
    `matKhau` VARCHAR(191) NOT NULL,
    `luongBatDau` DOUBLE NULL,
    `luongKetThuc` DOUBLE NULL,
    `trangThai` VARCHAR(191) NULL,
    `anhDaiDien` VARCHAR(191) NULL,

    PRIMARY KEY (`idNguoiDung`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VITRIUNGTUYEN` (
    `idViTri` INTEGER NOT NULL AUTO_INCREMENT,
    `tenViTri` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`idViTri`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TINHTHANH` (
    `idTinhThanh` INTEGER NOT NULL AUTO_INCREMENT,
    `tenTinhThanh` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`idTinhThanh`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CapDo` (
    `idCapDo` INTEGER NOT NULL AUTO_INCREMENT,
    `tenCapDo` VARCHAR(191) NOT NULL,
    `moTa` VARCHAR(191) NULL,

    PRIMARY KEY (`idCapDo`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOCVAN` (
    `idHocVan` INTEGER NOT NULL AUTO_INCREMENT,
    `noiHoc` VARCHAR(191) NOT NULL,
    `diaChi` VARCHAR(191) NULL,
    `nganhHoc` VARCHAR(191) NOT NULL,
    `diem` DOUBLE NULL,
    `idNguoiDung` INTEGER NOT NULL,

    PRIMARY KEY (`idHocVan`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KINHNGHIEM` (
    `idKinhNghiem` INTEGER NOT NULL AUTO_INCREMENT,
    `tenCongTy` VARCHAR(191) NOT NULL,
    `thoiGianBatDau` DATETIME(3) NOT NULL,
    `thoiGianKetThuc` DATETIME(3) NOT NULL,
    `diaChi` VARCHAR(191) NULL,
    `moTa` VARCHAR(191) NULL,
    `idNguoiDung` INTEGER NOT NULL,

    PRIMARY KEY (`idKinhNghiem`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DUAN` (
    `idDuAn` INTEGER NOT NULL AUTO_INCREMENT,
    `tenDuAn` VARCHAR(191) NOT NULL,
    `thoiGianBatDau` DATETIME(3) NOT NULL,
    `thoiGianKetThuc` DATETIME(3) NOT NULL,
    `congNghe` VARCHAR(191) NOT NULL,
    `link` VARCHAR(191) NULL,
    `idNguoiDung` INTEGER NOT NULL,

    PRIMARY KEY (`idDuAn`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KYNANG` (
    `idKyNang` INTEGER NOT NULL AUTO_INCREMENT,
    `idLoaiKN` INTEGER NOT NULL,
    `noiDung` VARCHAR(191) NOT NULL,
    `idNguoiDung` INTEGER NOT NULL,

    PRIMARY KEY (`idKyNang`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LoaiKN` (
    `idLoaiKN` INTEGER NOT NULL AUTO_INCREMENT,
    `tenKyNang` VARCHAR(191) NOT NULL,
    `moTa` VARCHAR(191) NULL,

    PRIMARY KEY (`idLoaiKN`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHUNGCHI` (
    `idChungChi` INTEGER NOT NULL AUTO_INCREMENT,
    `tenChungChi` VARCHAR(191) NOT NULL,
    `link` VARCHAR(191) NULL,
    `donViCap` VARCHAR(191) NULL,
    `idNguoiDung` INTEGER NOT NULL,

    PRIMARY KEY (`idChungChi`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THONGBAO` (
    `idThongBao` INTEGER NOT NULL AUTO_INCREMENT,
    `noiDung` VARCHAR(191) NOT NULL,
    `thoiGianTB` DATETIME(3) NOT NULL,
    `trangThai` VARCHAR(191) NULL,
    `idNguoiDung` INTEGER NOT NULL,
    `idBaiDang` INTEGER NOT NULL,

    PRIMARY KEY (`idThongBao`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BAIDANG` (
    `idBaiDang` INTEGER NOT NULL AUTO_INCREMENT,
    `idCongTy` INTEGER NOT NULL,
    `idTinhThanh` INTEGER NOT NULL,
    `tenBaiDang` VARCHAR(191) NOT NULL,
    `viTri` VARCHAR(191) NOT NULL,
    `soLuong` INTEGER NOT NULL,
    `trangThai` VARCHAR(191) NULL,
    `hinhAnh` VARCHAR(191) NULL,
    `luongBatDau` DOUBLE NOT NULL,
    `luongKetThuc` DOUBLE NOT NULL,
    `hanChot` DATETIME(3) NOT NULL,
    `ngayDang` DATETIME(3) NOT NULL,
    `ngaySua` DATETIME(3) NOT NULL,
    `diaChiCuThe` VARCHAR(191) NULL,

    PRIMARY KEY (`idBaiDang`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `YeuCau` (
    `idYeuCau` INTEGER NOT NULL AUTO_INCREMENT,
    `noiDung` VARCHAR(191) NOT NULL,
    `idBaiDang` INTEGER NOT NULL,

    PRIMARY KEY (`idYeuCau`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DANHSACH_UV` (
    `idBaiDang` INTEGER NOT NULL,
    `idNguoiDung` INTEGER NOT NULL,
    `thoiGianNop` DATETIME(3) NOT NULL,
    `trangThai` VARCHAR(191) NULL,

    PRIMARY KEY (`idBaiDang`, `idNguoiDung`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CONGTY` (
    `idCongTy` INTEGER NOT NULL AUTO_INCREMENT,
    `idLoaiTK` INTEGER NOT NULL,
    `tenCongTy` VARCHAR(191) NOT NULL,
    `diaChi` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `sDT` VARCHAR(191) NOT NULL,
    `linkWeb` VARCHAR(191) NULL,
    `nganhNghe` VARCHAR(191) NULL,
    `soLuongNhanVien` INTEGER NULL,
    `logo` VARCHAR(191) NULL,
    `trangThai` VARCHAR(191) NULL,
    `ngayThanhLap` DATETIME(3) NOT NULL,
    `moTa` VARCHAR(191) NULL,
    `matKhau` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`idCongTy`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `NGUOIDUNG` ADD CONSTRAINT `NGUOIDUNG_idLoaiTK_fkey` FOREIGN KEY (`idLoaiTK`) REFERENCES `LOAITAIKHOAN`(`idLoaiTK`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NGUOIDUNG` ADD CONSTRAINT `NGUOIDUNG_idViTri_fkey` FOREIGN KEY (`idViTri`) REFERENCES `VITRIUNGTUYEN`(`idViTri`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NGUOIDUNG` ADD CONSTRAINT `NGUOIDUNG_idTinhThanh_fkey` FOREIGN KEY (`idTinhThanh`) REFERENCES `TINHTHANH`(`idTinhThanh`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `NGUOIDUNG` ADD CONSTRAINT `NGUOIDUNG_idCapDo_fkey` FOREIGN KEY (`idCapDo`) REFERENCES `CapDo`(`idCapDo`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOCVAN` ADD CONSTRAINT `HOCVAN_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KINHNGHIEM` ADD CONSTRAINT `KINHNGHIEM_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DUAN` ADD CONSTRAINT `DUAN_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KYNANG` ADD CONSTRAINT `KYNANG_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KYNANG` ADD CONSTRAINT `KYNANG_idLoaiKN_fkey` FOREIGN KEY (`idLoaiKN`) REFERENCES `LoaiKN`(`idLoaiKN`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHUNGCHI` ADD CONSTRAINT `CHUNGCHI_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THONGBAO` ADD CONSTRAINT `THONGBAO_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THONGBAO` ADD CONSTRAINT `THONGBAO_idBaiDang_fkey` FOREIGN KEY (`idBaiDang`) REFERENCES `BAIDANG`(`idBaiDang`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BAIDANG` ADD CONSTRAINT `BAIDANG_idCongTy_fkey` FOREIGN KEY (`idCongTy`) REFERENCES `CONGTY`(`idCongTy`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `BAIDANG` ADD CONSTRAINT `BAIDANG_idTinhThanh_fkey` FOREIGN KEY (`idTinhThanh`) REFERENCES `TINHTHANH`(`idTinhThanh`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `YeuCau` ADD CONSTRAINT `YeuCau_idBaiDang_fkey` FOREIGN KEY (`idBaiDang`) REFERENCES `BAIDANG`(`idBaiDang`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANHSACH_UV` ADD CONSTRAINT `DANHSACH_UV_idBaiDang_fkey` FOREIGN KEY (`idBaiDang`) REFERENCES `BAIDANG`(`idBaiDang`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANHSACH_UV` ADD CONSTRAINT `DANHSACH_UV_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CONGTY` ADD CONSTRAINT `CONGTY_idLoaiTK_fkey` FOREIGN KEY (`idLoaiTK`) REFERENCES `LOAITAIKHOAN`(`idLoaiTK`) ON DELETE RESTRICT ON UPDATE CASCADE;
