-- DropForeignKey
ALTER TABLE `thongbao` DROP FOREIGN KEY `THONGBAO_idNguoiDung_fkey`;

-- AlterTable
ALTER TABLE `thongbao` ADD COLUMN `idCongTy` INTEGER NULL,
    MODIFY `idNguoiDung` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `THONGBAO` ADD CONSTRAINT `THONGBAO_idNguoiDung_fkey` FOREIGN KEY (`idNguoiDung`) REFERENCES `NGUOIDUNG`(`idNguoiDung`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THONGBAO` ADD CONSTRAINT `THONGBAO_idCongTy_fkey` FOREIGN KEY (`idCongTy`) REFERENCES `CONGTY`(`idCongTy`) ON DELETE SET NULL ON UPDATE CASCADE;
