-- AlterTable
ALTER TABLE `danhsach_uv` ADD COLUMN `diaChi` VARCHAR(191) NULL,
    ADD COLUMN `kieuPhongVan` VARCHAR(191) NULL,
    ADD COLUMN `link` VARCHAR(191) NULL,
    ADD COLUMN `thoiBatDau` VARCHAR(191) NULL;
