-- AlterTable
ALTER TABLE `capdo` ADD COLUMN `mucDo` INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE `tinhthanh` ADD COLUMN `kinhDo` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `viDo` DOUBLE NOT NULL DEFAULT 0;
