-- DropForeignKey
ALTER TABLE `congty` DROP FOREIGN KEY `CONGTY_idLoaiTK_fkey`;

-- AlterTable
ALTER TABLE `congty` MODIFY `idLoaiTK` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `CONGTY` ADD CONSTRAINT `CONGTY_idLoaiTK_fkey` FOREIGN KEY (`idLoaiTK`) REFERENCES `LOAITAIKHOAN`(`idLoaiTK`) ON DELETE SET NULL ON UPDATE CASCADE;
